# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/yt-utils',
                'doc_host': 'https://renato145.github.io',
                'git_url': 'https://github.com/renato145/yt-utils',
                'lib_path': 'yt_utils'},
  'syms': {'yt_utils.core': {'yt_utils.core.foo': ('core.html#foo', 'yt_utils/core.py')}}}
