# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['YTPlaylist']

# %% ../nbs/00_core.ipynb 5
class YTPlaylist:
    def __init__(self, data:dict): store_attr()

    def __repr__(self):
        flds = ['webpage_url', 'title', 'channel', 'playlist_count']
        sig = ', '.join(f'{o}={self.data[o]!r}' for o in flds)
        return f'YTPlaylist({sig})'

# %% ../nbs/00_core.ipynb 6
@patch(cls_method=True)
def from_url(cls:YTPlaylist, url: str)->YTPlaylist:
    with YoutubeDL({'flat_playlist': True, 'extract_flat': True, 'quiet': True}) as ydl:
        data = ydl.extract_info(url, download=False)
        return YTPlaylist(data)
